version: "3.9"

services:
  server-qgl:
    restart: always
    build: ./server/.
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    volumes:
      - ./server/public:/usr/src/app/public

  mongodb:
    restart: always
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MDB_ADMIN_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MDB_ADMIN_PWD}
      - KOALABODB_NAME=${KOALABODB_NAME}
      - KOALABODB_PWD=${KOALABODB_PWD}
    ports:
      - 27017:27017
    volumes:
      - ./database/init/:/docker-entrypoint-initdb.d/:ro
      - ./database/db:/data/db
